name: CD Pipeline

on:
  push:
    branches:
      - devel
      - stage
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '15.5.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.REGION }}

      - name: Deploy
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ vars.S3_BUCKET }}
          bucket-region: ${{ vars.REGION }}
          dist-id: ${{ vars.CF_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          private: true
          files-to-include: '{.*/**,**}'
